apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapp
spec:
  selector:
    matchLabels:
      app: orderapp
  replicas: 1
  template:
    metadata:
      labels:
        app: orderapp
    spec:
      containers:
        - name: orderapp
          image: utkubalikci/orderapp:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
